### ISSUE TITLE
Nightshade breaks the converter 

### ISSUE THREAD

**Issue by Fallon999** [xXxTheDarkprogramerxXx/PS3Tools#22] opened 2019-07-13 10:49 UTC
Trying to convert the Nightshade(PAL) iso with the 1.0.0.15 version causes the icon image to disappear and when trying to create the .pkg it forever stall at moving data.

**Comment by xXxTheDarkprogramerxXx** [comment] 2019-07-14 12:06
Can you please supply me with the ps2 id of the game so i can test this on my end

**Comment by Fallon999** [comment] 2019-07-15 06:38
Sorry for the late response. I wasnt checking my emails yesterday. The ID
is: SLES52238

ne 14. 7. 2019 o 14:06 xXxTheDarkprogramerxXx <notifications@github.com>
napísal(a):

**Comment by xXxTheDarkprogramerxXx** [comment] 2019-07-15 07:03
Bug Reproduced seems to be because i did not have this is ps2 tools i will add a small fix for this 

It will be in the next update 

Kind Regards

**Comment by xXxTheDarkprogramerxXx** [comment] 2019-07-16 05:30
This seems to be a result of the ps2 tools image URL works fine in browser but not on the app's ui 

I have added a new option for you to the File Section of the GUI 
![image](https://user-images.githubusercontent.com/12253240/61268228-1d9b5780-a79b-11e9-83a7-fb8878edb3f3.png)

The Replace Cover Image should be enough for the package to build 

I have made a successful build on the latest unreleased version of ps2 classics gui which will be 1.0.0.16 

Also with the Default Emulator specified in settings

**Closed as completed by xXxTheDarkprogramerxXx** 2019-07-16 05:30 UTC
Labels: bug
